spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: zltnb


logging:
  level:
    root: info
    com.zlt.blog: debug
  file:
    name: log/blog-dev.log