spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

comment.avatar: /images/avatar.jpg

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml